export const BLOG_POST_EXAMPLE = `
# @yanshoof/types
`

export const timetable_example = [
  [
    {},
    {
      subject: 'חנג בנים',
      teacher: 'חניה אריה',
      class: '',
      changes: [{ modification: 1 }],
    },
    { subject: 'תנ"ך', teacher: 'קוסיאק עינת', class: 'חדר יא 2' },
    {
      subject: 'מדעי המחשב יח"ל 4-5',
      teacher: 'גרוסמן לילך',
      class: 'חדר מחשב שכבה ט',
    },
    {
      subject: 'מדעי המחשב יח"ל 4-5',
      teacher: 'גרוסמן לילך',
      class: 'חדר מחשב שכבה ט',
    },
    { subject: 'פיזיקה', teacher: 'גרייזל יוסי', class: 'כימיה מעבדה 2' },
    { subject: 'תנ"ך', teacher: 'קוסיאק עינת', class: 'חדר יא 2' },
    {
      subject: 'מתמטיקה 5',
      teacher: 'רוזנבלום כרמית',
      class: 'חדר יא 6 אקוסטי',
    },
    { subject: 'אנגלית 5', teacher: 'לואיס אינגריד', class: 'חדר יא 3' },
    { subject: 'אנגלית 5', teacher: 'לואיס אינגריד', class: 'חדר יא 3' },
    {},
    {},
    {},
  ],
  [
    {},
    { subject: 'אנגלית 5', teacher: 'לואיס אינגריד', class: 'חדר יא 3' },
    { subject: 'אנגלית 5', teacher: 'לואיס אינגריד', class: 'חדר יא 3' },
    { subject: 'הבעה ולשון', teacher: 'סלומון רונית', class: 'חדר יא 2' },
    { subject: 'הבעה ולשון', teacher: 'סלומון רונית', class: 'חדר יא 2' },
    { subject: 'הבעה ולשון', teacher: 'סלומון רונית', class: 'חדר יא 2' },
    { subject: 'היסטוריה', teacher: 'גדסי פריד אורנית', class: 'חדר יא 2' },
    { subject: 'פיזיקה', teacher: 'גרייזל יוסי', class: 'פיזיקה מעבדה 2' },
    { subject: 'פיזיקה', teacher: 'גרייזל יוסי', class: 'פיזיקה מעבדה 2' },
    { subject: 'פיזיקה', teacher: 'גרייזל יוסי', class: 'פיזיקה מעבדה 2' },
    {},
    {},
    {},
  ],
  [
    {},
    {
      subject: 'ספרות',
      teacher: 'כץ אפודי סלעית',
      class: 'חדר יא 2',
      changes: [{ modification: 1 }],
    },
    { subject: 'תנ"ך', teacher: 'קוסיאק עינת', class: 'חדר יא 2' },
    {
      subject: 'מתמטיקה 5',
      teacher: 'רוזנבלום כרמית',
      class: 'חדר יא 6 אקוסטי',
      changes: [{ modification: 3, modData: 'ישראל ישראלי' }],
    },
    {
      subject: 'מתמטיקה 5',
      teacher: 'רוזנבלום כרמית',
      class: 'חדר יא 6 אקוסטי',
      events: ['מבחן שכבתי בלשון'],
    },
    { subject: 'ספרות', teacher: 'כץ אפודי סלעית', class: 'חדר יא 2' },
    {
      subject: 'הבעה ולשון',
      teacher: 'סלומון רונית',
      class: 'חדר יא 2',
      changes: [
        { modification: 5, modData: 'תנ"ך' },
        { modification: 3, modData: 'אבי כהן' },
      ],
    },
    {
      subject: 'מדעי המחשב יח"ל 4-5',
      teacher: 'גרוסמן לילך',
      class: 'חדר מחשב שכבה ט',
      changes: [{ modification: 6, modData: 'מבחן בלשון שכבת יא' }],
    },
    {},
    {},
    {},
    {},
    {},
  ],
  [
    { subject: 'מבט', teacher: 'כץ אפודי סלעית', class: 'מקוון סינכרוני' },
    {},
    {},
    {},
    { subject: 'ספרות', teacher: 'כץ אפודי סלעית', class: 'חדר יא 2' },
    { subject: 'לומד עצמאי היסטוריה', teacher: '', class: '' },
    { subject: 'לומד עצמאי היסטוריה', teacher: '', class: '' },
    {},
    {},
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {},
    {},
    { subject: 'היסטוריה', teacher: 'גדסי פריד אורנית', class: 'חדר יא 2' },
    { subject: 'ספרות', teacher: 'כץ אפודי סלעית', class: 'חדר יא 2' },
    {},
    {},
    { subject: 'חינוך', teacher: 'כץ אפודי סלעית', class: 'חדר יא 2' },
    {},
    {},
    {},
    {},
    {},
  ],
  [
    {},
    {},
    {},
    {
      subject: 'הנדסת תוכנה אפליקציה',
      teacher: 'נבון בסיס מירי',
      class: 'חדר מחשב שכבה ט',
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
  ],
  [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
]
